version: '3.8'

services:
  db:
    image: ${POSTGRES_VERSION:-postgres:15-alpine}
    container_name: kalana
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Jakarta
      PGTZ: Asia/Jakarta
    ports:
      - "${DB_PORT_EXTERNAL:-5434}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kalana-network

  api:
    build: 
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: kalana-api
    restart: always
    ports:
      - "${API_PORT_EXTERNAL:-3000}:3000" 
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TZ=Asia/Jakarta
    depends_on:
      - db
    networks:
      - kalana-network

networks:
  kalana-network:
    driver: bridge

volumes:
  postgres_data:
    external: ${DB_VOLUME_EXTERNAL:-false}
    name: ${DB_VOLUME_NAME:-postgres_data}