version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: kalana
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kalanacommerce
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kalana-network

  api:
    build: .
    container_name: kalana-api
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    networks:
      - kalana-network

networks:
  kalana-network:
    driver: bridge

volumes:
  postgres_data: